name: Java-CI-deploy-jobs

on:
  workflow_run:
    workflows: [Java-CI-Build-Maven, Java-CI-Build-Gradle]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check if Workflow 1 completed
        id: Java-CI-Build-Gradle
        run: |
          echo "Java-CI-Build-Gradle Conclusion: ${{ github.event.workflow_run.conclusion }}"

      - name: Check if Workflow 2 completed
        id: Java-CI-Build-Maven
        run: |
          echo "Java-CI-Build-Maven Conclusion: ${{ github.event.workflow_run.conclusion }}"

      - name: Proceed to next step only if both workflows are completed
        if: |
          ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          echo "Both Java-CI-Build-Gradle and Java-CI-Build-Maven are complete. Now running the next task."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1